### ISSUE TITLE
vcfwave create incorrect phased genotypes

### ISSUE THREAD

**Issue by Han-Cao** [vcflib/vcflib#403]
**Describe the bug**

In the output of `vcfwave`, the phased genotypes are not consistent with the input VCF.

**To Reproduce**

Here are some examples of the incorrect phased genotypes.

Input VCF records:
```
chr1	791616	>32685013>32685003	AATGGA	A,AATGGAATGGA	60.0	.	AC=1,1;AF=0.333333,0.333333;AN=2;AT=>32685013>32685012>32685003,>32685013>32685003,>32685013>32685012<32685011>32685003;NS=2;LV=0	GT	2|1
chr1	1368204	>32721851>32721861	TTTTTTTT	TTTTTTTTTTTTTTT,T	60.0	.	AC=0,2;AF=0.333333,0.666667;AN=2;AT=>32721851>32721852>32721853>32721854>32721855>32721856>32721861,>32721851>32721852>32721853>32721854>32721855>32721856>32721857>32721858>32721859>32721860>32721861,>32721851>32721861;NS=2;LV=0	GT	2|2
```

Output VCF records:
```
chr1	791616	>32685013>32685003_1	AATGGA	A	60	.	AC=1;AF=0.333333;AN=2;AT=>32685013>32685012>32685003;NS=2;LV=0;ORIGIN=chr1:791616;LEN=5;INV=0;TYPE=del	GT	0|1
chr1	791621	>32685013>32685003_2	A	AATGGA	60	.	AC=1;AF=0.000000;AN=-1;AT=;NS=2;LV=0;ORIGIN=chr1:791616;LEN=5;INV=0;TYPE=ins	GT	0|1
chr1	1368204	>32721851>32721861_1	TTTTTTTT	T	60	.	AC=2;AF=0.666667;AN=2;AT=>32721851>32721852>32721853>32721854>32721855>32721856>32721857>32721858>32721859>32721860>32721861;NS=2;LV=0;ORIGIN=chr1:1368204;LEN=7;INV=0;TYPE=del	GT	1|1
chr1	1368211	>32721851>32721861_2	T	TTTTTTTT	60	.	AC=2;AF=0.000000;AN=-1;AT=;NS=2;LV=0;ORIGIN=chr1:1368204;LEN=7;INV=0;TYPE=ins	GT	1|1
```

**Expected behavior**

For the first record: `chr1	791616	>32685013>32685003	AATGGA	A,AATGGAATGGA`, the sample has genotype `2|1`. The expected output is:
```
chr1	791616	>32685013>32685003_1	AATGGA	A	GT	0|1
chr1	791621	>32685013>32685003_2	A	AATGGA	GT	1|0
```
while vcfwave output `0|1` for `>32685013>32685003_2`. The phase conflict with each other.

For the second record: `chr1	1368204	>32721851>32721861	TTTTTTTT	TTTTTTTTTTTTTTT,T`, the genotype is `2|2`, which indicate a homozygous deletion. The expected output is:
```
chr1	1368204	>32721851>32721861_1	TTTTTTTT	T	GT	1|1
chr1	1368211	>32721851>32721861_2	T	TTTTTTTT	GT	0|0
```
while vcfwave output `1|1` for the insertion `>32721851>32721861_2`.

**Comment by Han-Cao** [comment]
I find other issues with the output INFO of vcfwave, you can replicate this with HPRCv1.1 VCFs:
- hprc-v1.1-mc-chm13.raw.vcf.gz: https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.raw.vcf.gz
- hprc-v1.1-mc-chm13.vcfbub.a100k.wave.vcf.gz: https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.vcfbub.a100k.wave.vcf.gz
```
bcftools view -H -r chr22:11021446-11021447 -s HG01109 hprc-v1.1-mc-chm13.raw.vcf.gz
chr22   11021446        >55070592>55070595      TT      T,TTT   60      .       AC=1,0;AF=0.0857143,0.0571429;AN=2;AT=>55070592>55070593>55070595,>55070592>55070595,>55070592>55070593>55070594>55070595;NS=44;LV=0    GT      0|1

bcftools view -H -r chr22:11021446-11021447 -s HG01109 hprc-v1.1-mc-chm13.vcfbub.a100k.wave.vcf.gz
[W::bcf_calc_ac] Incorrect number of AC fields at chr22:11021447. (This message is printed only once.)

chr22   11021446        >55070592>55070595_1    TT      T       60      .       AC=1;AF=0.085714;AN=2;AT=>55070592>55070593>55070595;NS=44;LV=0;ORIGIN=chr22:11021446;LEN=1;TYPE=del    GT      0|1
chr22   11021447        >55070592>55070595_2    T       TT      60      .       AC=1;AF=0.0857143,0.0571429;AN=2;AT=>55070592>55070593>55070595,>55070592>55070595,>55070592>55070593>55070594>55070595;NS=44;LV=0;ORIGIN=chr22:11021446;LEN=1;TYPE=ins  GT      0|1
```

In raw VCF:

- For variant `>55070592>55070595  TT  T,TTT`, HG01109 has genotype ` 0|1`
- The AT for the reference (TT) and alternative alleles (T, TTT) are >55070592>55070593>55070595, >55070592>55070595, and >55070592>55070593, respecitvely

In vcfwave output
- HG01109 has `0|1` for both TT -> T and TT -> TTT alleles on the same haplotype, which is incorrect and impossible
- The AT of >55070592>55070595_1 is incorrectly shown as the reference allele's AT (>55070592>55070593>55070595). It looks like vcfwave treat the first AT value as the first alternative allele (i.e., Number=A) instead of the reference allele (i.e., Number=R)
- For >55070592>55070595_2, the INFO is the same as the input record and not updated.

**Comment by glennhickey** [comment]
Yeah, this looks like a serious bug in that `vcfwave` does not seem to be able to correctly handle multi-allelic records.  

I wonder if splitting a priori with `bcftools norm -m -any` would be a fix.  @ekg is this a known thing? 

For the tags, I think it's normal that the `AT` tags are invalid since the VCF no longer (necessarily) corresponds to the graph.  The correct thing to do is to just drop them all, I'd think.  

Thanks

**Comment by ekg** [comment]
This looks bad. Can you please share a reproducible example? CC @pjotrp we should figure this out!

**Comment by Han-Cao** [comment]
Hi @ekg,

I generate a small test VCF using of the above 3 examples:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=CONFLICT,Number=.,Type=String,Description="Sample names for which there are multiple paths in the graph with conflicting alleles">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=LV,Number=1,Type=Integer,Description="Level in the snarl tree (0=top level)">
##INFO=<ID=PS,Number=1,Type=String,Description="ID of variant corresponding to parent snarl">
##INFO=<ID=AT,Number=R,Type=String,Description="Allele Traversal as path in graph">
##contig=<ID=chr1,length=248387328>
##contig=<ID=chr22,length=51324926>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample
chr1	791616	>32685013>32685003	AATGGA	A,AATGGAATGGA	60.0	.	AC=1,1;AF=0.333333,0.333333;AN=2;AT=>32685013>32685012>32685003,>32685013>32685003,>32685013>32685012<32685011>32685003;NS=2;LV=0	GT	2|1
chr1	1368204	>32721851>32721861	TTTTTTTT	TTTTTTTTTTTTTTT,T	60.0	.	AC=0,2;AF=0.333333,0.666667;AN=2;AT=>32721851>32721852>32721853>32721854>32721855>32721856>32721861,>32721851>32721852>32721853>32721854>32721855>32721856>32721857>32721858>32721859>32721860>32721861,>32721851>32721861;NS=2;LV=0	GT	2|2
chr22	11021446	>55070592>55070595	TT	T,TTT	60	.	AC=1,0;AF=0.0857143,0.0571429;AN=2;AT=>55070592>55070593>55070595,>55070592>55070595,>55070592>55070593>55070594>55070595;NS=44;LV=0	GT	0|1
```
The output of `vcfwave test.vcf` is:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=CONFLICT,Number=.,Type=String,Description="Sample names for which there are multiple paths in the graph with conflicting alleles">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=LV,Number=1,Type=Integer,Description="Level in the snarl tree (0=top level)">
##INFO=<ID=PS,Number=1,Type=String,Description="ID of variant corresponding to parent snarl">
##INFO=<ID=AT,Number=R,Type=String,Description="Allele Traversal as path in graph">
##contig=<ID=chr1,length=248387328>
##contig=<ID=chr22,length=51324926>
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of allele, either snp, mnp, ins, del, or complex.">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="allele length">
##INFO=<ID=ORIGIN,Number=1,Type=String,Description="Decomposed from a complex record using vcflib vcfwave and alignment with WFA2-lib.">
##INFO=<ID=INV,Number=A,Type=String,Description="Count of haplotypes which are aligned in the inverted orientation using vcflib vcfwave.">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample
chr1	791616	>32685013>32685003_1	AATGGA	A	60	.	AC=1;AF=0.333333;AN=2;AT=>32685013>32685012>32685003;NS=2;LV=0;ORIGIN=chr1:791616;LEN=5;INV=0;TYPE=del	GT	0|1
chr1	791621	>32685013>32685003_2	A	AATGGA	60	.	AC=1;AF=0.000000;AN=-1;AT=;NS=2;LV=0;ORIGIN=chr1:791616;LEN=5;INV=0;TYPE=ins	GT	0|1
chr1	1368204	>32721851>32721861_1	TTTTTTTT	T	60	.	AC=2;AF=0.666667;AN=2;AT=>32721851>32721852>32721853>32721854>32721855>32721856>32721857>32721858>32721859>32721860>32721861;NS=2;LV=0;ORIGIN=chr1:1368204;LEN=7;INV=0;TYPE=del	GT	1|1
chr1	1368211	>32721851>32721861_2	T	TTTTTTTT	60	.	AC=2;AF=0.000000;AN=-1;AT=;NS=2;LV=0;ORIGIN=chr1:1368204;LEN=7;INV=0;TYPE=ins	GT	1|1
chr22	11021446	>55070592>55070595_1	TT	T	60	.	AC=1;AF=0.085714;AN=2;AT=>55070592>55070593>55070595;NS=44;LV=0;ORIGIN=chr22:11021446;LEN=1;INV=0;TYPE=del	GT	0|1
chr22	11021447	>55070592>55070595_2	T	TT	60	.	AC=1;AF=0.000000;AN=-1;AT=;NS=44;LV=0;ORIGIN=chr22:11021446;LEN=1;INV=0;TYPE=ins	GT	0|1
```

**Comment by glennhickey** [comment]
Here's the example upthread with a header attached
```
wget -q http://public.gi.ucsc.edu/~hickey/debug/vcfwave-region.vcf.gz
wget -q http://public.gi.ucsc.edu/~hickey/debug/vcfwave-region.vcf.gz.tbi
vcfwave vcfwave-region.vcf.gz
```
this gives the wrong genotypes, but also garbles the first record 
```
chr22ogr11021446.22%    >55070592>55070595_1████TT██████T███████60██████.▏ ▏    AC=1;AF=0.085714;AN=2;AT=>55070592>55070593>55070595;NS=44;LV=0;ORIGIN=chr22:11021446;LEN=1;TYPE=del    GT      0|1
chr22   11021447        >55070592>55070595_2    T       TT      60      .       AC=1,0;AF=0.0857143,0.0571429;AN=2;AT=>55070592>55070593>55070595,>55070592>55070595,>55070592>55070593>55070594>55070595;NS=44;LV=0;ORIGIN=chr22:11021446;LEN=1;TYPE=ins       GT      0|1

**Comment by Han-Cao** [comment]
Hi @ekg and @glennhickey,

I just found vcfwave may also output incorrect genotypes for biallelic input.

In the below example, all SNPs' genotypes are missing. But they are not overlapped with any deletions

Input VCF:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=CONFLICT,Number=.,Type=String,Description="Sample names for which there are multiple paths in the graph with conflicting alleles">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=LV,Number=1,Type=Integer,Description="Level in the snarl tree (0=top level)">
##INFO=<ID=PS,Number=1,Type=String,Description="ID of variant corresponding to parent snarl">
##INFO=<ID=AT,Number=R,Type=String,Description="Allele Traversal as path in graph">
##contig=<ID=chr1,length=248387328>
##contig=<ID=chr22,length=51324926>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S1	S2
chr1	1288215	test	TCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCCCGAGTCTCTGCTCCGTCCCGTGTCTGCTCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCTCTGCTCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCC	CCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCTCTGCTCCGTCCCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCT	60	.	AC=3;AF=0.75;AN=4;AT=>1>2,>1>3	GT	0|1	1|1
```
vcfwave output:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=CONFLICT,Number=.,Type=String,Description="Sample names for which there are multiple paths in the graph with conflicting alleles">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=LV,Number=1,Type=Integer,Description="Level in the snarl tree (0=top level)">
##INFO=<ID=PS,Number=1,Type=String,Description="ID of variant corresponding to parent snarl">
##INFO=<ID=AT,Number=R,Type=String,Description="Allele Traversal as path in graph">
##contig=<ID=chr1,length=248387328>
##contig=<ID=chr22,length=51324926>
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of allele, either snp, mnp, ins, del, or complex.">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="allele length">
##INFO=<ID=ORIGIN,Number=1,Type=String,Description="Decomposed from a complex record using vcflib vcfwave and alignment with WFA2-lib.">
##INFO=<ID=INV,Number=A,Type=String,Description="Count of haplotypes which are aligned in the inverted orientation using vcflib vcfwave.">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S1	S2
chr1	1288215	test_1	T	C	60	.	AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;INV=0;TYPE=snp	GT	.|.	.|.
chr1	1288233	test_2	T	C	60	.	AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;INV=0;TYPE=snp	GT	.|.	.|.
chr1	1288240	test_3	C	CCCGTGTCTCTGCTCCGTCCCCC	60	.	AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=22;INV=0;TYPE=ins	GT	0|1	1|1
chr1	1288280	test_4	A	T	60	.	AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;INV=0;TYPE=snp	GT	.|.	.|.
chr1	1288302	test_5	T	TCTGCCCCGTCCCGTGTCCCT	60	.	AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=20;INV=0;TYPE=ins	GT	0|1	1|1
chr1	1288318	test_6	C	T	60	.	AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;INV=0;TYPE=snp	GT	.|.	.|.
chr1	1288356	test_7	TCTGCTCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCC	T	60	.	AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=36;INV=0;TYPE=del	GT	0|1	1|1
```

If I remove the deletion from input (i.e., trim CTGCTCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCC at the end of input REF allele), all genotypes are correct:
Input:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  S1      S2
chr1    1288215 test    TCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCCCGAGTCTCTGCTCCGTCCCGTGTCTGCTCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCT  CCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCTCTGCTCCGTCCCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCT  60      .       AC=3;AF=0.75;AN=4;AT=>1>2,>1>3  GT      0|1     1|1
```
Output:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  S1      S2
chr1    1288215 test_1  T       C       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;INV=0;TYPE=snp  GT      0|1     1|1
chr1    1288233 test_2  T       C       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;INV=0;TYPE=snp  GT      0|1     1|1
chr1    1288240 test_3  C       CCCGTGTCTCTGCTCCGTCCCCC 60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=22;INV=0;TYPE=ins GT      0|1     1|1
chr1    1288280 test_4  A       T       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;INV=0;TYPE=snp  GT      0|1     1|1
chr1    1288302 test_5  T       TCTGCCCCGTCCCGTGTCCCT   60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=20;INV=0;TYPE=ins GT      0|1     1|1
chr1    1288318 test_6  C       T       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;INV=0;TYPE=snp  GT      0|1     1|1
```

**Comment by AndreaGuarracino** [comment]
@Han-Cao , @glennhickey, can you try the latest version of `vcflib`/`vcfwave`? A few weeks ago I've applied a fix that resolved some `vcfwave` output issues. Trying it on the examples reported by @Han-Cao, I get

```shell
grep '^#' -v x.vcf | column -t 
chr1  791616   >32685013>32685003  AATGGA    A,AATGGAATGGA      60.0  .  AC=1,1;AF=0.333333,0.333333;AN=2;AT=>32685013>32685012>32685003,>32685013>32685003,>32685013>32685012<32685011>32685003;NS=2;LV=0                                                                                                     GT  2|1
chr1  1368204  >32721851>32721861  TTTTTTTT  TTTTTTTTTTTTTTT,T  60.0  .  AC=0,2;AF=0.333333,0.666667;AN=2;AT=>32721851>32721852>32721853>32721854>32721855>32721856>32721861,>32721851>32721852>32721853>32721854>32721855>32721856>32721857>32721858>32721859>32721860>32721861,>32721851>32721861;NS=2;LV=0  GT  2|2

vcfwave x.vcf -q | grep '^#' -v | column -t
chr1  791616   >32685013>32685003_1  AATGGA    A         60  .  AC=1;AF=0.333333;AN=2;AT=>32685013>32685012>32685003;NS=2;LV=0;ORIGIN=chr1:791616;LEN=5;TYPE=del                                                                           GT  0|1
chr1  791621   >32685013>32685003_2  A         AATGGA    60  .  AC=1;AF=0.333333;AN=2;AT=>32685013>32685003;NS=2;LV=0;ORIGIN=chr1:791616;LEN=5;TYPE=ins                                                                                    GT  1|0
chr1  1368204  >32721851>32721861_1  TTTTTTTT  T         60  .  AC=2;AF=0.666667;AN=2;AT=>32721851>32721852>32721853>32721854>32721855>32721856>32721857>32721858>32721859>32721860>32721861;NS=2;LV=0;ORIGIN=chr1:1368204;LEN=7;TYPE=del  GT  1|1
chr1  1368211  >32721851>32721861_2  T         TTTTTTTT  60  .  AC=0;AF=0.333333;AN=2;AT=>32721851>32721852>32721853>32721854>32721855>32721856>32721861;NS=2;LV=0;ORIGIN=chr1:1368204;LEN=7;TYPE=ins                                      GT  0|0
```

```shell
zgrep '^#' vcfwave-region.vcf.gz -v | column -t
chr22  11021446  >55070592>55070595  TT  T,TTT  60  .  AC=1,0;AF=0.0857143,0.0571429;AN=2;AT=>55070592>55070593>55070595,>55070592>55070595,>55070592>55070593>55070594>55070595;NS=44;LV=0  GT  0|1

vcfwave vcfwave-region.vcf.gz -q | grep '^#' -v | column -t
chr22  11021446  >55070592>55070595_1  TT  T   60  .  AC=1;AF=0.085714;AN=2;AT=>55070592>55070593>55070595;NS=44;LV=0;ORIGIN=chr22:11021446;LEN=1;TYPE=del  GT  0|1
chr22  11021447  >55070592>55070595_2  T   TT  60  .  AC=0;AF=0.057143;AN=2;AT=>55070592>55070595;NS=44;LV=0;ORIGIN=chr22:11021446;LEN=1;TYPE=ins           GT  0|0
```

It seems part (not all) of the issues are fixed with the latest `vcfwave`.

**Comment by Han-Cao** [comment]
Hi @AndreaGuarracino ,

Just tried the latest `vcfwave` and it works well for the tested multi-allelic records. But it still incorrectly output missing genotypes for some SNPs that are not overlapped by deletion. One reproducible example input is:

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=CONFLICT,Number=.,Type=String,Description="Sample names for which there are multiple paths in the graph with conflicting alleles">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=LV,Number=1,Type=Integer,Description="Level in the snarl tree (0=top level)">
##INFO=<ID=PS,Number=1,Type=String,Description="ID of variant corresponding to parent snarl">
##INFO=<ID=AT,Number=R,Type=String,Description="Allele Traversal as path in graph">
##contig=<ID=chr1,length=248387328>
##contig=<ID=chr22,length=51324926>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S1	S2
chr1	1288215	test	TCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCCCGAGTCTCTGCTCCGTCCCGTGTCTGCTCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCTCTGCTCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCC	CCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCTCTGCTCCGTCCCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCTCTGCTCCGTCCCGTGTCTCTGCCCCGTCCCCCGTGTCT	60	.	AC=3;AF=0.75;AN=4;AT=>1>2,>1>3	GT	0|1	1|1
```

Output:
```
chr1    1288215 test_1  T       C       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;TYPE=snp        GT      .|.     .|.
chr1    1288233 test_2  T       C       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;TYPE=snp        GT      .|.     .|.
chr1    1288240 test_3  C       CCCGTGTCTCTGCTCCGTCCCCC 60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=22;TYPE=ins       GT      0|1     1|1
chr1    1288280 test_4  A       T       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;TYPE=snp        GT      .|.     .|.
chr1    1288302 test_5  T       TCTGCCCCGTCCCGTGTCCCT   60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=20;TYPE=ins       GT      0|1     1|1
chr1    1288318 test_6  C       T       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=1;TYPE=snp        GT      .|.     .|.
chr1    1288356 test_7  TCTGCTCCGTCCCGTGTCCCTGCTCCGTCCCGTGTCC   T       60      .       AC=3;AF=0.750000;AN=4;AT=>1>2;ORIGIN=chr1:1288215;LEN=36;TYPE=del       GT      0|1     1|1
```

**Comment by AndreaGuarracino** [comment]
@Han-Cao I was already cooking to fix also that case! #408
